### ISSUE TITLE
Initialize app using API authentication token and include in all calls

### ISSUE THREAD

**Issue by abrinckm** [abrinckm/TE-Performer-App#46]

**Comment by swyngaard** [comment]
Resolved with commits [7e2429b](https://github.com/abrinckm/TE-Performer-App/commit/7e2429b24b35891fde3854875d8e4113741dddb2) and [8e22912](https://github.com/abrinckm/TE-Performer-App/commit/8e22912a6d1719e55f1320efee399bbddb108455)
