### ISSUE TITLE
Multi-Node Server (Worker)

### ISSUE THREAD

**Issue by AMarczak** [abrinckm/TE-Performer-App#65]

**Comment by abrinckm** [comment]
I don't believe Multi-node is the correct solution for what we need.
Multi-node is an http server that spawns multiple processes for concurrently handling incoming requests. It is a persvr project written specifically for service APIs at persvr. 

We don't need an http server, what we need instead is the ability to send requests in parallel to the T&E API.

**Comment by ian-taylor** [comment]
I don't understand this.  We need to both receive multi simultaneous requests (from the python task generator) and send these requests in  to the T&E API. So, we need a server or another mechanism to pass requests from Python to a running nodeJS program, right?

**Comment by abrinckm** [comment]
Right, but the multi-node thing is the exact reverse of that. It accepts http requests on behalf of some API and sends out messages to the spawned workers via TCP or IPC. 

So, Node.js can do exactly what you described without the need of anything extra. We can fork 4 Node workers from the master, and the each worker will just listen to any stdout messages from the python task generator. I'm thinking it’s as easy as the following javascript “py.stdout.on(‘task’, function(){…});” where the function will handle the task message and send a request to the API. Forking workers is very trivial.
